version: '3.8'

services:
  database:
    image: mysql:8
    container_name: grocery-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: GroceryDB
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: grocery-api
    restart: always
    depends_on:
      - database
    environment:
      DB_HOST: localhost
      DB_NAME: GroceryDB
      DB_USER: root
      DB_PASSWORD: root
      PORT: 7070
    ports:
      - "7070:7070"
    volumes:
      - .:/app
      - /app/node_modules

volumes:
  mysql_data:
